name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build C++ Application
        run: |
          cl.exe credstore.cpp /link Advapi32.lib

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: credstore
          path: credstore.exe
